### ISSUE TITLE
other games support 

### ISSUE THREAD

**Issue by dananothername** [DemoJameson/Cuphead.macOStoLinux#1]
can this tool work for all mac games 
or can you tell how this tool work

**Comment by DemoJameson** [comment]
No, it only works for Cuphead

Just follow this guide https://www.gamingonlinux.com/wiki/Unity_Games_Working_On_Linux_(User_Ported)
It is better to download the corresponding version of Unity Editor to compile a game and observe the corresponding location of the files in different systems.
